-- Based on https://github.com/oracle-samples/db-sample-schemas
-- Licensed under MIT License https://github.com/oracle-samples/db-sample-schemas/blob/main/LICENSE.txt 

CREATE TABLE "REGIONS" (
	"REGION_ID" SERIAL  NOT NULL,
	"REGION_NAME" CHARACTER VARYING(25),
	CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID"),
	CONSTRAINT "REGION_ID_NN" CHECK ("REGION_ID" IS NOT NULL)
);

CREATE TABLE "COUNTRIES" (
	"COUNTRY_ID" CHARACTER (2) NOT NULL,
	"COUNTRY_NAME" CHARACTER VARYING(60),
	"REGION_ID" INTEGER NOT NULL,
	CONSTRAINT "COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID"),
	CONSTRAINT "COUNTR_REG_FK" FOREIGN KEY ("REGION_ID") REFERENCES "REGIONS" ("REGION_ID"),
	CONSTRAINT "COUNTRY_ID_NN" CHECK ("COUNTRY_ID" IS NOT NULL)
);

CREATE TABLE "LOCATIONS" (
	"LOCATION_ID" SERIAL NOT NULL,
	"STREET_ADDRESS" CHARACTER VARYING(80),
	"CITY" CHARACTER VARYING(30) NOT NULL,
	"COUNTRY" CHARACTER VARYING(30) NOT NULL,
	"COUNTRY_CODE" CHARACTER(20),
	"POSTAL_CODE" CHARACTER VARYING(50),
	CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID"),
	CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_CODE") REFERENCES "COUNTRIES" ("COUNTRY_ID"),
	CONSTRAINT "LOC_CITY_NN" CHECK ("CITY" IS NOT NULL)
);

CREATE TABLE "JOBS" (
	"JOB_ID" SERIAL NOT NULL,
	"JOB_TITLE" CHARACTER VARYING(35) NOT NULL,
	"MIN_SALARY" NUMERIC (8, 2),
	"MAX_SALARY" NUMERIC (8, 2),
	CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID"),
	CONSTRAINT "JOB_TITLE_NN" CHECK ("JOB_TITLE" IS NOT NULL)
);

CREATE TABLE "DEPARTMENTS" (
	"DEPARTMENT_ID" SERIAL NOT NULL,
	"DEPARTMENT_NAME" CHARACTER VARYING(50) NOT NULL,
	"MANAGER_ID" INTEGER,
	"LOCATION_ID" INTEGER,
	CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID"),
	CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATIONS" ("LOCATION_ID"),
	CONSTRAINT "DEPT_NAME_NN" CHECK ("DEPARTMENT_NAME" IS NOT NULL)
);

CREATE TABLE "EMPLOYEES" (
	"EMPLOYEE_ID" SERIAL NOT NULL,
	"FIRST_NAME" CHARACTER VARYING(20),
	"LAST_NAME" CHARACTER VARYING(25) NOT NULL,
	"EMAIL" CHARACTER VARYING(80) NOT NULL,
	"PHONE_NUMBER" CHARACTER VARYING(20),
	"HIRE_DATE" TIMESTAMP (6) NOT NULL,
	"JOB_ID" CHARACTER VARYING(10) NOT NULL,
	"SALARY" NUMERIC (8,2),
	"COMMISSION_PCT" DECIMAL(2,2),
	"MANAGER_ID" INTEGER,
	"DEPARTMENT_ID" INTEGER,
	CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID"),
	CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID"),
	CONSTRAINT "EMP_JOB_FK" FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID"),
	CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES" ("EMPLOYEE_ID"),
	CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL"),
	CONSTRAINT "EMP_SALARY_MIN" CHECK ("SALARY" > 0),
	CONSTRAINT "EMP_JOB_NN" CHECK ("JOB_ID" IS NOT NULL),
	CONSTRAINT "EMP_HIRE_DATE_NN" CHECK ("HIRE_DATE" IS NOT NULL),
	CONSTRAINT "EMP_EMAIL_NN" CHECK ("EMAIL" IS NOT NULL),
	CONSTRAINT "EMP_LAST_NAME_NN" CHECK ("LAST_NAME" IS NOT NULL)
);

ALTER TABLE "DEPARTMENTS"
ADD ( CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES" ("EMPLOYEE_ID") );
