CREATE TABLE "REGIONS" (
	"REGION_ID" INTEGER NOT NULL,
	"REGION_NAME" VARCHAR(25),
	CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID"),
	CONSTRAINT "REGION_ID_NN" CHECK ("REGION_ID" IS NOT NULL)
);

CREATE TABLE "COUNTRIES" (
	"COUNTRY_ID" CHAR(20) NOT NULL,
	"COUNTRY_NAME" VARCHAR(40),
	"REGION_ID" INTEGER,
	CONSTRAINT "COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID"),
	CONSTRAINT "COUNTR_REG_FK" FOREIGN KEY ("REGION_ID") REFERENCES "REGIONS" ("REGION_ID"),
	CONSTRAINT "COUNTRY_ID_NN" CHECK ("COUNTRY_ID" IS NOT NULL)
);

CREATE TABLE "LOCATIONS" (
	"LOCATION_ID" SMALLINT NOT NULL,
	"STREET_ADDRESS" VARCHAR(40),
	"CITY" VARCHAR(30) NOT NULL,
	"COUNTRY" VARCHAR(30) NOT NULL,
	"COUNTRY_CODE" CHAR(20),
	"POSTAL_CODE" VARCHAR(50),
	CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID"),
	CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_CODE") REFERENCES "COUNTRIES" ("COUNTRY_ID"),
	CONSTRAINT "LOC_CITY_NN" CHECK ("CITY" IS NOT NULL)
);

CREATE TABLE "JOBS" (
	"JOB_ID" VARCHAR(10) NOT NULL,
	"JOB_TITLE" VARCHAR(35) NOT NULL,
	"MIN_SALARY" INTEGER,
	"MAX_SALARY" INTEGER,
	CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID"),
	CONSTRAINT "JOB_TITLE_NN" CHECK ("JOB_TITLE" IS NOT NULL)
);

CREATE TABLE "DEPARTMENTS" (
	"DEPARTMENT_ID" INT NOT NULL,
	"DEPARTMENT_NAME" VARCHAR(30) NOT NULL,
	"MANAGER_ID" INT,
	"LOCATION_ID" SMALLINT,
	CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID"),
	CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATIONS" ("LOCATION_ID"),
	CONSTRAINT "DEPT_NAME_NN" CHECK ("DEPARTMENT_NAME" IS NOT NULL)
);

CREATE TABLE "EMPLOYEES" (
	"EMPLOYEE_ID" INT NOT NULL,
	"FIRST_NAME" VARCHAR(20),
	"LAST_NAME" VARCHAR(25) NOT NULL,
	"EMAIL" VARCHAR(50) NOT NULL,
	"PHONE_NUMBER" VARCHAR(20),
	"HIRE_DATE" TIMESTAMP (6) NOT NULL,
	"JOB_ID" VARCHAR(10) NOT NULL,
	"SALARY" DECIMAL(8,2),
	"COMMISSION_PCT" DECIMAL(2,2),
	"MANAGER_ID" INT,
	"DEPARTMENT_ID" SMALLINT,
	CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID"),
	CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS" ("DEPARTMENT_ID"),
	CONSTRAINT "EMP_JOB_FK" FOREIGN KEY ("JOB_ID") REFERENCES "JOBS" ("JOB_ID"),
	CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES" ("EMPLOYEE_ID"),
	CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL"),
	CONSTRAINT "EMP_SALARY_MIN" CHECK ("SALARY" > 0),
	CONSTRAINT "EMP_JOB_NN" CHECK ("JOB_ID" IS NOT NULL),
	CONSTRAINT "EMP_HIRE_DATE_NN" CHECK ("HIRE_DATE" IS NOT NULL),
	CONSTRAINT "EMP_EMAIL_NN" CHECK ("EMAIL" IS NOT NULL),
	CONSTRAINT "EMP_LAST_NAME_NN" CHECK ("LAST_NAME" IS NOT NULL)
);
