CREATE USER denodo WITH PASSWORD 'denodo';
CREATE DATABASE denodo_cache OWNER denodo;
GRANT ALL PRIVILEGES ON DATABASE denodo_cache TO denodo;
CREATE DATABASE denodo OWNER denodo;
GRANT ALL PRIVILEGES ON DATABASE denodo TO denodo;
CREATE DATABASE sso OWNER denodo;
GRANT ALL PRIVILEGES ON DATABASE sso TO denodo;
CREATE DATABASE denodo_monitor OWNER denodo;
GRANT ALL PRIVILEGES ON DATABASE denodo_monitor TO denodo;