
  CREATE TABLE "OL_SERVICE_REQUEST" 
   (	"SR_ID" INTEGER NOT NULL, 
	"SR_DATE" TIMESTAMP (6) NOT NULL, 
	"SR_DESCRIPTION" VARCHAR(2000) NOT NULL, 
	"CUSTOMER_IP" VARCHAR(100) NOT NULL, 
	"GLOBAL_CASE_ID" INTEGER NOT NULL, 
	"CASE_CREATION_DATE" TIMESTAMP (6), 
	"CASE_CLOSED_DATE" VARCHAR (60), 
	"CASE_SUMMARY" VARCHAR(2000) NOT NULL, 
	"STATUS_CODE" DECIMAL(38,0) NOT NULL, 
	"STATUS_DESCRIPTION" VARCHAR(200), 
	"PROBLEM_ID" DECIMAL(38,0) NOT NULL, 
	"PROBLEM_DESCRIPTION" VARCHAR(200), 
	"CUSTOMER_CODE" VARCHAR(20), 
	"CUSTOMER_NAME" VARCHAR(50), 
	"CUSTOMER_ADDRESS" VARCHAR(100), 
	"CUSTOMER_PHONE" VARCHAR(20), 
	"CUSTOMER_JOB_TITLE" VARCHAR(50), 
	"AGENT_ID" INTEGER NOT NULL, 
	"AGENT_CODE" VARCHAR(20) NOT NULL, 
	"AGENT_NAME" VARCHAR(100) NOT NULL,
	CONSTRAINT "OL_SUPPORT_PK1" PRIMARY KEY ("SR_ID")
   );
