  CREATE TABLE "ORDERS" 
   (
    "ID" INTEGER NOT NULL, 
	"CUSTOMER_CODE" VARCHAR(20) NOT NULL, 
	"STATUS" VARCHAR(20) NOT NULL, 
	"DATE_PLACED" TIMESTAMP (6), 
	"DATE_DELIVERED" VARCHAR (60) , 
	"DATE_CLOSED" VARCHAR (60),
	CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID")
   )  ;
   

   CREATE TABLE "ORDER_ITEM" 
   (
    "ID" INTEGER NOT NULL, 
	"ORDER_ID" INTEGER NOT NULL, 
	"PRODUCT_ID" INTEGER NOT NULL,
	CONSTRAINT "ORDER_ITEM_PK" PRIMARY KEY ("ID")
   ) ;

   CREATE TABLE "CUSTOMER" 
   (	"ID" INTEGER NOT NULL, 
	"CUSTOMER_CODE_INTERNAL" VARCHAR(20) NOT NULL, 
	"FIRST_NAME" VARCHAR(50) NOT NULL, 
	"LAST_NAME" VARCHAR(100), 
	"EMAIL" VARCHAR(50) NOT NULL, 
	"PHONE" VARCHAR(20), 
	"MAIN_ADDRESS" VARCHAR(200), 
	"MAIN_POSTCODE" VARCHAR(20), 
	"MAIN_COUNTRY" VARCHAR(100), 
	"REGISTERED_DATE" TIMESTAMP (6) NOT NULL,
	CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("ID", "CUSTOMER_CODE_INTERNAL")
   ) ;